# -*- coding: utf-8 -*-
"""Atividade_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HZG6vvQ8QRtRVzdzPVU7BjWvCrbYKIRm
"""

# Montagem de Genoma/Algoritmo guloso
# Objetivo: montar sequência Contig a partir de reads
# Aprendizado> Algoritmos gulosos, alinhamento, sequenciamento de DNA, reads e Contig

# Algoritmos gulosos (Greedy Algorithms) são utilizados para a montagem de Genomas (Genoma Assembly) após o sequenciamento de fragmentos de DNA de um cromossomo. O primeiro passo do sequenciamento de genoma é fragmentar o cromossomo, depois amplificar os fragmentos utilizando PCR e sequenciar os fragmentos. Os fragmentos sequenciados são chamados de "reads". Comparando as sequências dos reads, encontram-se região que se sobrepõe, essas regiões sobrepostas são fundidas/montadas na sequência final chamada de "contig".

# Tarefa: a partir de 4 sequências curtas de DNA sequenciado, arquivo "reads.fasta" , faça um código que monte o Contig correspondente. Salve o contig em arquivo no formato FASTA. Exemplo de nome: contig.fasta.  Veja vídeo com instruções, explicando a atividade


# Arquivo fasta com sequências de DNA - as reads
# Vídeo explicando como montar genoma. Ver como a partir dos reads monta um contig

# Enviar:
# 1 - código que monta o contig a partir dos reads
# 2 - arquivo no formato fasta com a sequência do contig.

!pip install biopython

from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio import SeqIO

# Carregar as sequências curtas a partir do arquivo FASTA
reads_file = "reads4.fasta"
reads = list(SeqIO.parse(reads_file, "fasta"))

# Organizar as sequências curtas pelo tamanho decrescente
reads.sort(key=lambda x: len(x.seq), reverse=True)

# Montar o Contig
contig_seq = reads[0].seq
for read in reads[1:]:
    read_seq = read.seq
    overlap = contig_seq.find(read_seq[:len(read_seq) // 2])
    contig_seq = contig_seq[:overlap] + read_seq

# Criar objeto SeqRecord para o Contig
contig_record = SeqRecord(Seq(contig_seq), id="Contig", description="Contig montado a partir de sequências curtas")

# Salvar o Contig em um arquivo FASTA
contig_file = "contig.fasta"
SeqIO.write(contig_record, contig_file, "fasta")

print("Contig salvo com sucesso no arquivo contig.fasta.")